### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by ijainot78** [ElectricGun/cheat-codes-mod#2]
what button should i press?

**Comment by ElectricGun** [comment]
type out the codes on your keyboard without any typos

**Comment by Timon4ikRU** [comment]
> type out the codes on your keyboard without any typos
 in console?

**Comment by ElectricGun** [comment]
anywhere in-game, console works too

**Comment by Enot1998** [comment]
Можно пожалуйста конкретно. Просто влуюом месте игры чит не действует 🤝

**Comment by Luchezr** [comment]
> как открыть консоль

Настройки > игра > включить консоль > выйди из настроек > клавиша"F8' (по умолчанию. Уточни в настройках управления, в самом низу)

**Comment by Timon4ikRU** [comment]
Я так делал, не работает от слова СОВСЕМ

**Comment by MaZ1Kk7887** [comment]
> вводите коды на клавиатуре без каких-либо опечаток

What if I play on my phone, what should I do?

**Comment by ElectricGun** [comment]
mobile support done
