### ISSUE TITLE
Router

### ISSUE THREAD

**Issue by 1ue999** [ElectricGun/cheat-codes-mod#4]
fills the map with routers (yes, even replaces terrain and cores) code: "router"
a simple 2-layer for loop?

**Comment by 1ue999** [comment]
ill just finish the code real quick... then ima make merge request i think?

**Comment by 1ue999** [comment]
i just gotta fix some nullPointerExeptions

**Comment by 1ue999** [comment]
current code is at 1ue999/cheat-codes-mod

**Comment by ElectricGun** [comment]
Closing because fork doesn't exist

**Comment by traincrisis** [comment]
@1ue999 can you please unblock me on steam pleaseee

**Comment by traincrisis** [comment]
![Знімок екрана з 2024-08-27 15-18-19](https://github.com/user-attachments/assets/db06aa02-1edb-4b67-aaf2-30864063a10e)
noooooo
